### ISSUE TITLE
2G/3G toggle 

### ISSUE THREAD

**Issue by MSNTSK** [baikalos/UserVoice#18]
Please add 2G/3G toggle in suspend actions and feature to set position of clock in statusbar

**Comment by sdv22** [comment]
There is an option to switch to 2G on screen off. Switching to 3G has no meaning, cause it doesn't save any juice.

**Comment by MSNTSK** [comment]
OK. Understand, shame because when I'm listening online radio 2G mobile data internet speed is too low and music stop playing...
