### ISSUE TITLE
Энергосбережение

### ISSUE THREAD

**Issue by mjhmjhgkmj** [baikalos/UserVoice#35]
Есть проблема в энергосбережении. Я видел ее в нескольких прошивках pie.

При включении режима энергосбережения (батарейка во вешней шторке) приложения принудительно закрываются.
Например я работал в браузере, свернул его, позвонил, вернулся в браузер, а он перезапускается. Если при этом нет сети то я не увижу страницу. Если я набивал текст ответа, то текст будет потерян.

Такое поведение неприемлемо, поэтому я не могу пользоваться режимом энергосбережения.
Нельзя ли внести изменения в этот режим, чтобы неактивные приложения не выгружались из памяти?

**Comment by sdv22** [comment]
Так решил Гугл. И это правильное поведение для режима энергоcбережения. Все приложения отсутствующие в белом списке и не являющиеся системными ограничиваются в фоне.
Если их не убивать, смысл режима теряется.

**Comment by mjhmjhgkmj** [comment]
Как редактировать "белый список"?

**Comment by sdv22** [comment]
BaikalOS Extras->Power Save->Whitelist->Все приложения->Приложения->не экономить.

**Comment by mjhmjhgkmj** [comment]
да, нашел
приложения - выбрать - батарея - ограничение в фоновом режиме
странно, раньше там не видел

спасибо

**Comment by mjhmjhgkmj** [comment]
да, или через BaikalOS Extras

**Comment by sdv22** [comment]
Ограничение работы в фоновм режиме - это не белый список. Это приложения с принудительным ограничением. Ограничения в baikalos распространяются не только на режим сбережения энергии.
