### ISSUE TITLE
Баг сканера отпечатков Le Pro 3 (Fingerprint after reboot issue)

### ISSUE THREAD

**Issue by Korvin1608** [baikalos/UserVoice#4]
Добавляется отпечаток, после перезагрузки его нет в списке отпечатков, снова его добавить не возможно (ну один и тот же палец раза 2 можно и все) и не распознается.

**Comment by andr68rus** [comment]
Пофиксил. Должно теперь работать (со следующей сборки).
Решение: https://github.com/baikalos/frameworks_base/commit/7c39280357a93db1efecd7d71d7f579d06036bad

**Comment by andr68rus** [comment]
Решено, закрываю.
