### ISSUE TITLE
Include Gapps in rom because opengapps does not overwrite stock google apps 

### ISSUE THREAD

**Issue by amittalnagpur** [baikalos/UserVoice#45]
Include Gapps in rom because opengapps does not overwrite stock google apps like google contact, dialer, message because opengapps facing issue  #672 of (Keep the stock dialer by default, instead of as configuration due to emergency calls not functioning properly sometimes. #672). So, could you please add gapps in rom because user have to download your rom which size is aprox 740 mb and PLUS opengapps so its better if you include in it.

**Comment by sdv22** [comment]
GAPPS will never be included on BaikalOS. Not all the users use google services. Some oth them are from countries where access is blocked.
