### ISSUE TITLE
Переключатель быстрой зарядки

### ISSUE THREAD

**Issue by DJEscHGL** [baikalos/UserVoice#5]

**Comment by Hawkm3x** [comment]
В целом, кому-то удобно так ставить на ночь будет, может быть. В любом случае тумблер хуже ничего не сделает, а для кого-то дополнительный функционал.

**Comment by andr68rus** [comment]
Если Серега на уровне ядра ее пофиксит, тумблер добавить не проблема.

**Comment by sdv22** [comment]
Сделаю. Там давное известно что и где. Криворукие мерджильщики читать комменты не умеют.
