### ISSUE TITLE
[Предложение] Погода

### ISSUE THREAD

**Issue by Grant2k** [baikalos/UserVoice#74]
Прошу добавить погоду из OMNI
![screenshot_ _20190205-202145](https://user-images.githubusercontent.com/29144739/52295219-e58a2000-2983-11e9-8135-2ab741357c01.png)
![screenshot_omnijaws_20190205-202155](https://user-images.githubusercontent.com/29144739/52295220-e58a2000-2983-11e9-8b00-04f7cafe40e4.png)

**Comment by sdv22** [comment]
use third party apps. openweathermap has too much issues, especialy with the default omni API key.
