### ISSUE TITLE
[Bug] Задвоение отображения скорости интернета в статусбаре

### ISSUE THREAD

**Issue by rugineer** [baikalos/UserVoice#76]
Аппарат - x2, прошивка - Baikal-OS-P-x2-OFFICIAL-20190213-1324. Двойное отображение скорости данных в статусной строке.
<a href="https://ibb.co/vYxZP8P"><img src="https://i.ibb.co/q5Mksws/Baikal-OS-P-x2-OFFICIAL-20190213-1324.jpg" alt="Baikal-OS-P-x2-OFFICIAL-20190213-1324" border="0"></a>

**Comment by rugineer** [comment]
В версии Baikal-OS-P-x2-OFFICIAL-20190213-1636 баг исправлен. Issue можно закрывать.

**Comment by sdv22** [comment]
fixed
