### ISSUE TITLE
[Bug]Не отображаются цифры скорости трафика в статусбаре, когда он тёмный

### ISSUE THREAD

**Issue by rugineer** [baikalos/UserVoice#85]
Телефон: x2
Прошивка: Baikal-OS-P-x2-OFFICIAL-20190306-1610
Не отображаются скорости трафика на черном фоне, появляется только стрелочки.
На белом - нормально

**Comment by BePozzzitive** [comment]
Присоединюсь телефон тот же

**Comment by rugineer** [comment]
Трафик отображается, но не зависимо от цвета статусбара черным цветом

**Comment by rugineer** [comment]
В прошивке Baikal-OS-P-x2-OFFICIAL-20190310-1545 баг исправлен, можно закрывать
