### ISSUE TITLE
Видео запись экрана (Screenrecording)

### ISSUE THREAD

**Issue by Hawkm3x** [baikalos/UserVoice#9]
На кастомах, в том числе и на RR если не ошибаюсь есть твик записи экрана (такой же как на скриншот в шторке).Добавьте эту функцию если есть такая возможность, было бы очень удобно иметь такой рекордер.

**Comment by BollexN1** [comment]
Дополню. Функция записи есть так же и на Nitrogen, так что думаю есть от куда дернуть))
Встроенная запись всегда удобнее стороннего приложения.

**Comment by Saggoth** [comment]
@BollexN1 верно

**Comment by andr68rus** [comment]
Сделаем

**Comment by andr68rus** [comment]
Сделано. Completed.
